var srcIndex = JSON.parse('{\
"ads1x1x":["",[["devices",[["features",[],["mod.rs","tier1.rs","tier2.rs"]],["mode",[],["continuous.rs","mod.rs","oneshot.rs"]]],["common.rs","mod.rs"]]],["channels.rs","construction.rs","conversion.rs","ic.rs","interface.rs","lib.rs","types.rs"]],\
"aho_corasick":["",[["nfa",[],["contiguous.rs","mod.rs","noncontiguous.rs"]],["packed",[["teddy",[],["compile.rs","mod.rs","runtime.rs"]]],["api.rs","mod.rs","pattern.rs","rabinkarp.rs","vector.rs"]],["util",[],["alphabet.rs","buffer.rs","byte_frequencies.rs","debug.rs","error.rs","int.rs","mod.rs","prefilter.rs","primitives.rs","remapper.rs","search.rs","special.rs"]]],["ahocorasick.rs","automaton.rs","dfa.rs","lib.rs","macros.rs"]],\
"ak09915_rs":["",[],["lib.rs"]],\
"approx":["",[],["abs_diff_eq.rs","lib.rs","macros.rs","relative_eq.rs","ulps_eq.rs"]],\
"bitflags":["",[],["external.rs","internal.rs","iter.rs","lib.rs","parser.rs","public.rs","traits.rs"]],\
"bitvec":["",[["array",[],["api.rs","iter.rs","ops.rs","traits.rs"]],["boxed",[],["api.rs","iter.rs","ops.rs","traits.rs"]],["field",[],["io.rs"]],["macros",[],["internal.rs"]],["ptr",[],["addr.rs","proxy.rs","range.rs","single.rs","span.rs"]],["slice",[["specialization",[],["lsb0.rs","msb0.rs"]]],["api.rs","iter.rs","ops.rs","specialization.rs","traits.rs"]],["vec",[],["api.rs","iter.rs","ops.rs","traits.rs"]]],["access.rs","array.rs","boxed.rs","devel.rs","domain.rs","field.rs","index.rs","lib.rs","macros.rs","mem.rs","order.rs","ptr.rs","slice.rs","store.rs","vec.rs","view.rs"]],\
"bmp280":["",[],["lib.rs"]],\
"byteorder":["",[],["io.rs","lib.rs"]],\
"cast":["",[],["lib.rs"]],\
"cfg_if":["",[],["lib.rs"]],\
"cpy_binder":["",[],["lib.rs"]],\
"embedded_hal":["",[["blocking",[],["can.rs","delay.rs","i2c.rs","mod.rs","rng.rs","serial.rs","spi.rs"]],["can",[],["id.rs","mod.rs","nb.rs"]],["digital",[],["mod.rs","v1.rs","v1_compat.rs","v2.rs","v2_compat.rs"]]],["adc.rs","fmt.rs","lib.rs","prelude.rs","serial.rs","spi.rs","timer.rs","watchdog.rs"]],\
"env_logger":["",[["filter",[],["mod.rs","regex.rs"]],["fmt",[["humantime",[],["extern_impl.rs","mod.rs"]],["writer",[["termcolor",[],["extern_impl.rs","mod.rs"]]],["atty.rs","mod.rs"]]],["mod.rs"]]],["lib.rs"]],\
"find_crate":["",[],["error.rs","lib.rs"]],\
"funty":["",[],["lib.rs"]],\
"getrandom":["",[],["error.rs","error_impls.rs","lib.rs","linux_android.rs","use_file.rs","util.rs","util_libc.rs"]],\
"gpio_cdev":["",[],["errors.rs","ffi.rs","lib.rs"]],\
"humantime":["",[],["date.rs","duration.rs","lib.rs","wrapper.rs"]],\
"i2cdev":["",[],["core.rs","ffi.rs","lib.rs","linux.rs","mock.rs"]],\
"icm20689":["",[["interface",[],["i2c.rs","mod.rs","spi.rs"]]],["lib.rs"]],\
"ioctl_rs":["",[["os",[],["linux.rs","mod.rs"]]],["lib.rs"]],\
"is_terminal":["",[],["lib.rs"]],\
"lazy_static":["",[],["inline_lazy.rs","lib.rs"]],\
"libc":["",[["unix",[["linux_like",[["linux",[["arch",[["generic",[],["mod.rs"]]],["mod.rs"]],["gnu",[["b64",[["x86_64",[],["align.rs","mod.rs","not_x32.rs"]]],["mod.rs"]]],["align.rs","mod.rs"]]],["align.rs","mod.rs","non_exhaustive.rs"]]],["mod.rs"]]],["align.rs","mod.rs"]]],["fixed_width_ints.rs","lib.rs","macros.rs"]],\
"linux_embedded_hal":["",[],["cdev_pin.rs","lib.rs","serial.rs","sysfs_pin.rs","timer.rs"]],\
"linux_raw_sys":["",[["x86_64",[],["errno.rs","general.rs","ioctl.rs"]]],["lib.rs"]],\
"log":["",[],["lib.rs","macros.rs"]],\
"memchr":["",[["memchr",[["x86",[],["avx.rs","mod.rs","sse2.rs"]]],["fallback.rs","iter.rs","mod.rs","naive.rs"]],["memmem",[["prefilter",[["x86",[],["avx.rs","mod.rs","sse.rs"]]],["fallback.rs","genericsimd.rs","mod.rs"]],["x86",[],["avx.rs","mod.rs","sse.rs"]]],["byte_frequencies.rs","genericsimd.rs","mod.rs","rabinkarp.rs","rarebytes.rs","twoway.rs","util.rs","vector.rs"]]],["cow.rs","lib.rs"]],\
"memoffset":["",[],["lib.rs","offset_of.rs","raw_field.rs","span_of.rs"]],\
"navigator":["",[],["lib.rs"]],\
"navigator_rs":["",[],["lib.rs"]],\
"nb":["",[],["lib.rs"]],\
"nix":["",[["mount",[],["linux.rs","mod.rs"]],["net",[],["if_.rs","mod.rs"]],["sys",[["ioctl",[],["linux.rs","mod.rs"]],["ptrace",[],["linux.rs","mod.rs"]],["socket",[],["addr.rs","mod.rs","sockopt.rs"]]],["aio.rs","epoll.rs","eventfd.rs","inotify.rs","memfd.rs","mman.rs","mod.rs","personality.rs","pthread.rs","quota.rs","reboot.rs","resource.rs","select.rs","sendfile.rs","signal.rs","signalfd.rs","stat.rs","statfs.rs","statvfs.rs","sysinfo.rs","termios.rs","time.rs","timerfd.rs","uio.rs","utsname.rs","wait.rs"]]],["dir.rs","env.rs","errno.rs","fcntl.rs","features.rs","ifaddrs.rs","kmod.rs","lib.rs","macros.rs","mqueue.rs","poll.rs","pty.rs","sched.rs","time.rs","ucontext.rs","unistd.rs"]],\
"num_traits":["",[["ops",[],["bytes.rs","checked.rs","euclid.rs","inv.rs","mod.rs","mul_add.rs","overflowing.rs","saturating.rs","wrapping.rs"]]],["bounds.rs","cast.rs","float.rs","identities.rs","int.rs","lib.rs","macros.rs","pow.rs","real.rs","sign.rs"]],\
"palette":["",[["alpha",[],["alpha.rs"]],["blend",[],["blend.rs","equations.rs","pre_alpha.rs"]],["encoding",[["pixel",[],["raw.rs"]]],["gamma.rs","linear.rs","pixel.rs","srgb.rs"]],["gradient",[],["named.rs"]],["luma",[],["luma.rs"]],["rgb",[["packed",[],["channels.rs"]]],["packed.rs","rgb.rs"]]],["alpha.rs","blend.rs","chromatic_adaptation.rs","color_difference.rs","component.rs","convert.rs","encoding.rs","equality.rs","float.rs","gradient.rs","hsl.rs","hsluv.rs","hsv.rs","hues.rs","hwb.rs","lab.rs","lch.rs","lchuv.rs","lib.rs","luma.rs","luv.rs","luv_bounds.rs","macros.rs","matrix.rs","named.rs","oklab.rs","oklch.rs","relative_contrast.rs","rgb.rs","white_point.rs","xyz.rs","yxy.rs"]],\
"palette_derive":["",[["alpha",[],["mod.rs","with_alpha.rs"]],["convert",[],["from_color_unclamped.rs","mod.rs","util.rs"]],["encoding",[],["mod.rs","pixel.rs"]],["meta",[],["field_attributes.rs","mod.rs","type_item_attributes.rs"]]],["lib.rs","util.rs"]],\
"phf":["",[],["lib.rs","map.rs","ordered_map.rs","ordered_set.rs","set.rs"]],\
"phf_generator":["",[],["lib.rs"]],\
"phf_macros":["",[],["lib.rs"]],\
"phf_shared":["",[],["lib.rs"]],\
"ppv_lite86":["",[["x86_64",[],["mod.rs","sse2.rs"]]],["lib.rs","soft.rs","types.rs"]],\
"proc_macro2":["",[],["detection.rs","extra.rs","fallback.rs","lib.rs","marker.rs","parse.rs","rcvec.rs","wrapper.rs"]],\
"pwm_pca9685":["",[],["channels.rs","config.rs","device_impl.rs","lib.rs","register_access.rs","types.rs"]],\
"quote":["",[],["ext.rs","format.rs","ident_fragment.rs","lib.rs","runtime.rs","spanned.rs","to_tokens.rs"]],\
"radium":["",[],["lib.rs","macros.rs","types.rs"]],\
"rand":["",[["distributions",[],["bernoulli.rs","distribution.rs","float.rs","integer.rs","mod.rs","other.rs","slice.rs","uniform.rs","utils.rs","weighted.rs","weighted_index.rs"]],["rngs",[["adapter",[],["mod.rs","read.rs","reseeding.rs"]]],["mock.rs","mod.rs","std.rs","thread.rs"]],["seq",[],["index.rs","mod.rs"]]],["lib.rs","prelude.rs","rng.rs"]],\
"rand_chacha":["",[],["chacha.rs","guts.rs","lib.rs"]],\
"rand_core":["",[],["block.rs","error.rs","impls.rs","le.rs","lib.rs","os.rs"]],\
"regex":["",[["regex",[],["bytes.rs","mod.rs","string.rs"]],["regexset",[],["bytes.rs","mod.rs","string.rs"]]],["builders.rs","bytes.rs","error.rs","find_byte.rs","lib.rs"]],\
"regex_automata":["",[["dfa",[],["mod.rs","onepass.rs","remapper.rs"]],["hybrid",[],["dfa.rs","error.rs","id.rs","mod.rs","regex.rs","search.rs"]],["meta",[],["error.rs","limited.rs","literal.rs","mod.rs","regex.rs","reverse_inner.rs","stopat.rs","strategy.rs","wrappers.rs"]],["nfa",[["thompson",[],["backtrack.rs","builder.rs","compiler.rs","error.rs","literal_trie.rs","map.rs","mod.rs","nfa.rs","pikevm.rs","range_trie.rs"]]],["mod.rs"]],["util",[["determinize",[],["mod.rs","state.rs"]],["prefilter",[],["aho_corasick.rs","byteset.rs","memchr.rs","memmem.rs","mod.rs","teddy.rs"]],["unicode_data",[],["mod.rs"]]],["alphabet.rs","captures.rs","empty.rs","escape.rs","int.rs","interpolate.rs","iter.rs","lazy.rs","look.rs","memchr.rs","mod.rs","pool.rs","primitives.rs","search.rs","sparse_set.rs","start.rs","syntax.rs","utf8.rs","wire.rs"]]],["lib.rs","macros.rs"]],\
"regex_syntax":["",[["ast",[],["mod.rs","parse.rs","print.rs","visitor.rs"]],["hir",[],["interval.rs","literal.rs","mod.rs","print.rs","translate.rs","visitor.rs"]],["unicode_tables",[],["mod.rs"]]],["debug.rs","either.rs","error.rs","lib.rs","parser.rs","rank.rs","unicode.rs","utf8.rs"]],\
"rppal":["",[["gpio",[],["epoll.rs","interrupt.rs","ioctl.rs","mem.rs","pin.rs","soft_pwm.rs"]],["i2c",[],["ioctl.rs"]],["pwm",[],["sysfs.rs"]],["spi",[],["ioctl.rs","segment.rs"]],["uart",[],["termios.rs"]]],["gpio.rs","i2c.rs","lib.rs","macros.rs","pwm.rs","spi.rs","system.rs","uart.rs"]],\
"rustix":["",[["backend",[["linux_raw",[["arch",[["asm",[],["mod.rs","x86_64.rs"]]],["mod.rs"]],["io",[],["errno.rs","mod.rs","syscalls.rs","types.rs"]],["termios",[],["mod.rs","syscalls.rs"]]],["c.rs","conv.rs","mod.rs","reg.rs"]]]],["io",[],["close.rs","dup.rs","errno.rs","fcntl.rs","ioctl.rs","mod.rs","read_write.rs"]],["maybe_polyfill",[["std",[],["mod.rs"]]]],["termios",[],["ioctl.rs","mod.rs","tc.rs","tty.rs","types.rs"]]],["bitcast.rs","cstr.rs","ffi.rs","lib.rs","pid.rs","utils.rs","weak.rs"]],\
"serde":["",[["de",[],["format.rs","ignored_any.rs","impls.rs","mod.rs","seed.rs","utf8.rs","value.rs"]],["private",[],["de.rs","doc.rs","mod.rs","ser.rs","size_hint.rs"]],["ser",[],["fmt.rs","impls.rs","impossible.rs","mod.rs"]]],["integer128.rs","lib.rs","macros.rs"]],\
"serde_derive":["",[],["buffer.rs","bytecode.rs","lib.rs","lib_precompiled.rs"]],\
"serial_core":["",[],["lib.rs"]],\
"serial_unix":["",[],["error.rs","lib.rs","poll.rs","tty.rs"]],\
"siphasher":["",[],["lib.rs","sip.rs","sip128.rs"]],\
"sk6812_rpi":["",[],["led.rs","lib.rs","strip.rs"]],\
"spidev":["",[],["lib.rs","spidevioctl.rs"]],\
"sysfs_gpio":["",[],["error.rs","lib.rs"]],\
"tap":["",[],["conv.rs","lib.rs","pipe.rs","tap.rs"]],\
"termcolor":["",[],["lib.rs"]],\
"termios":["",[["os",[],["linux.rs","mod.rs"]]],["ffi.rs","lib.rs"]],\
"toml":["",[],["datetime.rs","de.rs","lib.rs","macros.rs","map.rs","ser.rs","spanned.rs","tokens.rs","value.rs"]],\
"unicode_ident":["",[],["lib.rs","tables.rs"]],\
"void":["",[],["lib.rs"]],\
"wyz":["",[],["bidi.rs","comu.rs","fmt.rs","lib.rs","range.rs"]]\
}');
createSrcSidebar();
